name: infra

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
      - 'infra/**'
      - '.github/workflows/infra.yml'

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCOUNT_ID:      ${{ vars.AWS_ACCOUNT_ID }}
      AWS_DEPLOY_ROLE:     ${{ vars.AWS_DEPLOY_ROLE }}
      AWS_REGION:          ${{ vars.AWS_REGION }}
      TF_STATE_BUCKET:     ${{ vars.TF_STATE_BUCKET }}
      TF_STATE_LOCK_TABLE: ${{ vars.TF_STATE_LOCK_TABLE }}
      TF_IN_AUTOMATION:    true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_DEPLOY_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init (backend via flags)
        working-directory: infra/terraform
        run: |
          terraform init -input=false             -backend-config="bucket=${TF_STATE_BUCKET}"             -backend-config="key=global/terraform.tfstate"             -backend-config="region=${AWS_REGION}"             -backend-config="dynamodb_table=${TF_STATE_LOCK_TABLE}"             -backend-config="encrypt=true"

      - name: Terraform Validate
        working-directory: infra/terraform
        run: terraform validate

      - name: Terraform Apply (push to main or manual run on main)
        if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        working-directory: infra/terraform
        run: terraform apply -input=false -auto-approve
